version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=RGR-literature
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Prog_ram123
    ports:
      - '5432:5432'
    networks:
      - music-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d music"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/RGR-literature
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Prog_ram123
    ports:
      - '8080:8080'
    networks:
      - music-network

networks:
  music-network:
    driver: bridge

volumes:
  postgres-data:
